name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space Git Repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "deploy-bot@autotailor.io"
          git config --global user.name "AutoTailor Deploy Bot"
          git remote add hf https://huggingface.co/spaces/MakDvornikoff/AutoTailor || true
          git push --force https://MakDvornikoff:$HF_TOKEN@huggingface.co/spaces/MakDvornikoff/AutoTailor main
